services:
  - type: web
    name: dev-chba7-xza
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"